# rdme docs "\1" --version=1

rdme docs "doc/v1/PAPI feature catalog/" --version=1
rdme docs "doc/v1/PAPI feature catalog/behaviors-1/" --version=1
rdme docs "doc/v1/PAPI feature catalog/catalog-overview/" --version=1
rdme docs "doc/v1/PAPI feature catalog/criteria-1/" --version=1
rdme docs "doc/v1/PAPI feature catalog/v2020-03-04-rule-format/" --version=1
rdme docs "doc/v0/Build/" --version=1
rdme docs "doc/v0/Build/build/" --version=1
rdme docs "doc/v0/Bulk Property Activations/" --version=1
rdme docs "doc/v0/Bulk Property Activations/bulkactivations/" --version=1
rdme docs "doc/v0/Bulk Property Activations/bulkactivationsbulkactivationid/" --version=1
rdme docs "doc/v0/Bulk patches/" --version=1
rdme docs "doc/v0/Bulk patches/bulkrules-patch-requests/" --version=1
rdme docs "doc/v0/Bulk patches/bulkrules-patch-requestsbulkpatchid/" --version=1
rdme docs "doc/v0/Bulk search and update/" --version=1
rdme docs "doc/v0/Bulk search and update/become-a-power-user/" --version=1
rdme docs "doc/v0/Bulk search and update/bulk-activations/" --version=1
rdme docs "doc/v0/Bulk search and update/bulk-patches/" --version=1
rdme docs "doc/v0/Bulk search and update/bulk-searches/" --version=1
rdme docs "doc/v0/Bulk search and update/bulk-versioning/" --version=1
rdme docs "doc/v0/Bulk search and update/learn-about-bulk/" --version=1
rdme docs "doc/v0/Bulk search/" --version=1
rdme docs "doc/v0/Bulk search/bulkrules-search-requests/" --version=1
rdme docs "doc/v0/Bulk search/bulkrules-search-requestsbulksearchid/" --version=1
rdme docs "doc/v0/Bulk versioning/" --version=1
rdme docs "doc/v0/Bulk versioning/bulkproperty-version-creations/" --version=1
rdme docs "doc/v0/Bulk versioning/bulkproperty-version-creationsbulkcreateid/" --version=1
rdme docs "doc/v0/CP codes/" --version=1
rdme docs "doc/v0/CP codes/cpcodes/" --version=1
rdme docs "doc/v0/CP codes/cpcodescpcodeid/" --version=1
rdme docs "doc/v0/Client settings/" --version=1
rdme docs "doc/v0/Client settings/client-settings/" --version=1
rdme docs "doc/v0/Contracts/" --version=1
rdme docs "doc/v0/Contracts/contracts/" --version=1
rdme docs "doc/v0/Custom behaviors/" --version=1
rdme docs "doc/v0/Custom behaviors/custom-behaviors/" --version=1
rdme docs "doc/v0/Custom behaviors/custom-behaviorsbehaviorid/" --version=1
rdme docs "doc/v0/Custom overrides/" --version=1
rdme docs "doc/v0/Custom overrides/custom-overrides/" --version=1
rdme docs "doc/v0/Custom overrides/custom-overridesoverrideid/" --version=1
rdme docs "doc/v0/Edge hostnames/" --version=1
rdme docs "doc/v0/Edge hostnames/edgehostnames/" --version=1
rdme docs "doc/v0/Edge hostnames/edgehostnamesedgehostnameid/" --version=1
rdme docs "doc/v0/Errors/" --version=1
rdme docs "doc/v0/Errors/error-types/" --version=1
rdme docs "doc/v0/Groups/" --version=1
rdme docs "doc/v0/Groups/groups/" --version=1
rdme docs "doc/v0/Overview/" --version=1
rdme docs "doc/v0/Overview/basic-interaction/" --version=1
rdme docs "doc/v0/Overview/create/" --version=1
rdme docs "doc/v0/Overview/getting-started/" --version=1
rdme docs "doc/v0/Products/" --version=1
rdme docs "doc/v0/Products/products/" --version=1
rdme docs "doc/v0/Products/productsproductidmapping-use-cases/" --version=1
rdme docs "doc/v0/Properties/" --version=1
rdme docs "doc/v0/Properties/properties/" --version=1
rdme docs "doc/v0/Properties/propertiespropertyid/" --version=1
rdme docs "doc/v0/Property activations/" --version=1
rdme docs "doc/v0/Property activations/propertiespropertyidactivations/" --version=1
rdme docs "doc/v0/Property activations/propertiespropertyidactivationsactivationid/" --version=1
rdme docs "doc/v0/Property version hostnames/" --version=1
rdme docs "doc/v0/Property version hostnames/propertiespropertyidversionspropertyversionhostnames/" --version=1
rdme docs "doc/v0/Property version rules/" --version=1
rdme docs "doc/v0/Property version rules/propertiespropertyidversionspropertyversionrules/" --version=1
rdme docs "doc/v0/Property versions/" --version=1
rdme docs "doc/v0/Property versions/propertiespropertyidversions/" --version=1
rdme docs "doc/v0/Property versions/propertiespropertyidversionslatest/" --version=1
rdme docs "doc/v0/Property versions/propertiespropertyidversionspropertyversion/" --version=1
rdme docs "doc/v0/Property versions/propertiespropertyidversionspropertyversionavailable-behaviors/" --version=1
rdme docs "doc/v0/Property versions/propertiespropertyidversionspropertyversionavailable-criteria/" --version=1
rdme docs "doc/v0/Rule formats/" --version=1
rdme docs "doc/v0/Rule formats/rule-formats/" --version=1
rdme docs "doc/v0/Rule trees/" --version=1
rdme docs "doc/v0/Rule trees/interact-with-rules/" --version=1
rdme docs "doc/v0/Rule trees/rule-trees/" --version=1
rdme docs "doc/v0/Schemas/" --version=1
rdme docs "doc/v0/Schemas/schemasproductsproductidruleformat/" --version=1
rdme docs "doc/v0/Schemas/schemasrequestfilename/" --version=1
rdme docs "doc/v0/Search/" --version=1
rdme docs "doc/v0/Search/searchfind-by-value/" --version=1
rdme docs "doc/v0/Synchronous bulk search/" --version=1
rdme docs "doc/v0/Synchronous bulk search/bulkrules-search-requests-synch/" --version=1
rdme docs "doc/v0/Variables/" --version=1
rdme docs "doc/v0/Variables/learn-about-variables/" --version=1
rdme docs "doc/v1/" --version=1
rdme docs "doc/v1/Build/" --version=1
rdme docs "doc/v1/Build/build/" --version=1
rdme docs "doc/v1/Bulk Property Activations/" --version=1
rdme docs "doc/v1/Bulk Property Activations/bulkactivations/" --version=1
rdme docs "doc/v1/Bulk Property Activations/bulkactivationsbulkactivationid/" --version=1
rdme docs "doc/v1/Bulk patches/" --version=1
rdme docs "doc/v1/Bulk patches/bulkrules-patch-requests/" --version=1
rdme docs "doc/v1/Bulk patches/bulkrules-patch-requestsbulkpatchid/" --version=1
rdme docs "doc/v1/Bulk search and update/" --version=1
rdme docs "doc/v1/Bulk search and update/become-a-power-user/" --version=1
rdme docs "doc/v1/Bulk search and update/bulk-activations/" --version=1
rdme docs "doc/v1/Bulk search and update/bulk-patches/" --version=1
rdme docs "doc/v1/Bulk search and update/bulk-searches/" --version=1
rdme docs "doc/v1/Bulk search and update/bulk-versioning/" --version=1
rdme docs "doc/v1/Bulk search and update/learn-about-bulk/" --version=1
rdme docs "doc/v1/Bulk search/" --version=1
rdme docs "doc/v1/Bulk search/bulkrules-search-requests/" --version=1
rdme docs "doc/v1/Bulk search/bulkrules-search-requestsbulksearchid/" --version=1
rdme docs "doc/v1/Bulk versioning/" --version=1
rdme docs "doc/v1/Bulk versioning/bulkproperty-version-creations/" --version=1
rdme docs "doc/v1/Bulk versioning/bulkproperty-version-creationsbulkcreateid/" --version=1
rdme docs "doc/v1/CP codes/" --version=1
rdme docs "doc/v1/CP codes/cpcodes/" --version=1
rdme docs "doc/v1/CP codes/cpcodescpcodeid/" --version=1
rdme docs "doc/v1/Client settings/" --version=1
rdme docs "doc/v1/Client settings/client-settings/" --version=1
rdme docs "doc/v1/Contracts/" --version=1
rdme docs "doc/v1/Contracts/contracts/" --version=1
rdme docs "doc/v1/Custom behaviors/" --version=1
rdme docs "doc/v1/Custom behaviors/custom-behaviors/" --version=1
rdme docs "doc/v1/Custom behaviors/custom-behaviorsbehaviorid/" --version=1
rdme docs "doc/v1/Custom overrides/" --version=1
rdme docs "doc/v1/Custom overrides/custom-overrides/" --version=1
rdme docs "doc/v1/Custom overrides/custom-overridesoverrideid/" --version=1
rdme docs "doc/v1/Edge hostnames/" --version=1
rdme docs "doc/v1/Edge hostnames/edgehostnames/" --version=1
rdme docs "doc/v1/Edge hostnames/edgehostnamesedgehostnameid/" --version=1
rdme docs "doc/v1/Errors/" --version=1
rdme docs "doc/v1/Errors/error-types/" --version=1
rdme docs "doc/v1/Groups/" --version=1
rdme docs "doc/v1/Groups/groups/" --version=1
rdme docs "doc/v1/Overview/" --version=1
rdme docs "doc/v1/Overview/basic-interaction/" --version=1
rdme docs "doc/v1/Overview/create/" --version=1
rdme docs "doc/v1/Overview/getting-started/" --version=1
rdme docs "doc/v1/Products/" --version=1
rdme docs "doc/v1/Products/products/" --version=1
rdme docs "doc/v1/Products/productsproductidmapping-use-cases/" --version=1
rdme docs "doc/v1/Properties/" --version=1
rdme docs "doc/v1/Properties/properties/" --version=1
rdme docs "doc/v1/Properties/propertiespropertyid/" --version=1
rdme docs "doc/v1/Property activations/" --version=1
rdme docs "doc/v1/Property activations/propertiespropertyidactivations/" --version=1
rdme docs "doc/v1/Property activations/propertiespropertyidactivationsactivationid/" --version=1
rdme docs "doc/v1/Property version hostnames/" --version=1
rdme docs "doc/v1/Property version hostnames/propertiespropertyidversionspropertyversionhostnames/" --version=1
rdme docs "doc/v1/Property version rules/" --version=1
rdme docs "doc/v1/Property version rules/propertiespropertyidversionspropertyversionrules/" --version=1
rdme docs "doc/v1/Property versions/" --version=1
rdme docs "doc/v1/Property versions/propertiespropertyidversions/" --version=1
rdme docs "doc/v1/Property versions/propertiespropertyidversionslatest/" --version=1
rdme docs "doc/v1/Property versions/propertiespropertyidversionspropertyversion/" --version=1
rdme docs "doc/v1/Property versions/propertiespropertyidversionspropertyversionavailable-behaviors/" --version=1
rdme docs "doc/v1/Property versions/propertiespropertyidversionspropertyversionavailable-criteria/" --version=1
rdme docs "doc/v1/Rule formats/" --version=1
rdme docs "doc/v1/Rule formats/rule-formats/" --version=1
rdme docs "doc/v1/Rule trees/" --version=1
rdme docs "doc/v1/Rule trees/interact-with-rules/" --version=1
rdme docs "doc/v1/Rule trees/rule-trees/" --version=1
rdme docs "doc/v1/Schemas/" --version=1
rdme docs "doc/v1/Schemas/schemasproductsproductidruleformat/" --version=1
rdme docs "doc/v1/Schemas/schemasrequestfilename/" --version=1
rdme docs "doc/v1/Search/" --version=1
rdme docs "doc/v1/Search/searchfind-by-value/" --version=1
rdme docs "doc/v1/Synchronous bulk search/" --version=1
rdme docs "doc/v1/Synchronous bulk search/bulkrules-search-requests-synch/" --version=1
rdme docs "doc/v1/Variables/" --version=1
rdme docs "doc/v1/Variables/learn-about-variables/" --version=1
